# version: '3.8'
# Copyright (C) 2025 Joan Pastor
# License LGPL-3.0 or later (https://www.gnu.org/licenses/lgpl-3.0.html).

services:
  database:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - "./data/postgres_db:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo_user -d odoo_db"]
      interval: 5s
      start_period: 20s
      timeout: 60s
    restart: always

  odoo:
    build:
      context: .
      dockerfile: ./docker/dockerfile.dev.odoo
    container_name: odoo_app
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8069:8069"
      - "8071:8071"  # Livechat
    environment:
      ODOO_RC: /etc/odoo/odoo.conf
      PGHOST: ${POSTGRES_HOST}
      PGPORT: ${POSTGRES_PORT}
      PGDATABASE: ${POSTGRES_DB}
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - "./data/odoo_files:/var/lib/odoo"
      - "./addons:/mnt/extra-addons"
      - "./music:/music"
      - "./data/settings:/etc/odoo"
    restart: always

  navidrome:
    image: deluan/navidrome:latest
    # user: 1000:1000
    container_name: navidrome
    ports:
      - "4533:4533"
    environment:
      # Navidrome developing
      ND_DATAFOLDER: /data
      ND_MUSICFOLDER: /music
      ND_LOGLEVEL: warning

      # Navidrome behaviour
      ND_DEFAULTSHAREEXPIRATION: 24h
      ND_SCANINTERVAL: 1h
    volumes:
      - "./data/navidrome:/data"
      - "./music:/music:ro"
    restart: unless-stopped
